name: Upload Assets

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - run: yarn && yarn test
        name: Tests
